image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  CONTAINER_WEB_ROOT: "/var/www/localhost/drupal"
  SOLR_CORE: "d8"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  TEST_IMAGE: registry.gitlab.com/mog33/docker-images
  RELEASE_REGISTRY: docker.io
  RELEASE_IMAGE: index.docker.io/$RELEASE_USER

################################################################################
# Templates to avoid repeat.
# https://docs.gitlab.com/ee/ci/yaml/#anchors
################################################################################

.docker_login_gitlab:
  - &docker_login_gitlab docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

.docker_build_push:
  script: &docker_build_push
    - docker build --pull --tag $TEST_IMAGE/$IMAGE $DIR
    - docker push $TEST_IMAGE/$IMAGE

.docker_pull:
  - &docker_pull docker pull $TEST_IMAGE/$IMAGE

.build_image: &build_image
  stage: build
  before_script:
    - *docker_login_gitlab
  script: *docker_build_push

.test_image: &test_image
  stage: test
  before_script:
    - *docker_login_gitlab
    - *docker_pull
    - docker run -d -t --name test $TEST_IMAGE/$IMAGE

.test_solr: &test_solr
  <<: *test_image
  script:
    - docker exec --user=solr test wget -q -O - "http://localhost:8983/solr/${SOLR_CORE}/admin/ping"

.release: &release
  stage: release
  before_script:
    - docker login -u $RELEASE_USER -p $RELEASE_PASSWORD $RELEASE_REGISTRY
  script:
    - *docker_pull
    - docker tag $TEST_IMAGE/$IMAGE $RELEASE_IMAGE/$IMAGE
    - docker push $RELEASE_IMAGE/$IMAGE
  only:
    - master

.install_docker_compose: &install_docker_compose
  before_script:
    - apk --no-cache add make gettext bash python3 > /dev/null
    - python3 -m ensurepip > /dev/null
    - pip3 install --upgrade pip setuptools > /dev/null
    - if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip; fi > /dev/null
    - if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi > /dev/null
    - pip install 'docker-compose' > /dev/null

################################################################################
# Jobs based on previous templates.
################################################################################

solr:5:
  <<: *build_image
  variables:
    IMAGE: solr:5
    DIR: build/solr-5

test:solr:5:
  <<: *test_solr
  variables:
    IMAGE: solr:5

release:solr:5:
  <<: *release
  variables:
    IMAGE: solr:5

dashboard:
  <<: *build_image
  variables:
    IMAGE: dashboard:latest
    DIR: build/dashboard

test:dashboard:
  <<: *test_image
  script:
    - docker exec test wget -q --server-response "http://localhost:5000/blocks"
  variables:
    IMAGE: dashboard:latest

release:dashboard:
  <<: *release
  variables:
    IMAGE: dashboard:latest

.build:
  stage: build
  <<: *install_docker_compose
  script:
    - make setup
  cache:
    key: build
    paths:
      - .env
      - docker-compose.yml

.test php 7.1:
  stage: test
  <<: *install_docker_compose
  script:
    - make setup
    - touch report.txt
    - docker-compose config > report.txt
    - docker-compose build > /dev/null
    - docker-compose up -d
    - docker exec dcd-php php -v
    - if [ ! -f 'data/www/drupal/web/index.php' ];
      then
        docker exec dcd-php composer create-project drupal-composer/drupal-project:8.x-dev $CONTAINER_WEB_ROOT --stability dev --no-interaction --quiet;
      fi
    - if [ ! -d 'data/www/drupal/config/sync' ];
      then
        mkdir -p data/www/drupal/config/sync;
      fi
    - chmod -R 777 data/www/drupal/config/sync
    - scripts/drush si minimal -y
    - scripts/drush status
    - scripts/drush status >> report.txt
    - scripts/drupal site:status >> report.txt
    - scripts/composer show -P >> report.txt
  artifacts:
    paths:
      - report.txt
    expire_in: 1 hour
  cache:
    key: drupal
    paths:
      - data/www/drupal
      - data/database

.test php 7.2:
  stage: test
  <<: *install_docker_compose
  script:
    - make setup
    - touch report.txt
    - docker-compose config > report.txt
    - docker-compose build > /dev/null
    - sed -i 's#7.1#7.2#g' .env
    - docker-compose up -d
    - docker exec dcd-php php -v
    - if [ ! -f 'data/www/drupal/web/index.php' ];
      then
        docker exec dcd-php composer create-project drupal-composer/drupal-project:8.x-dev $CONTAINER_WEB_ROOT --stability dev --no-interaction --quiet;
      fi
    - if [ ! -d 'data/www/drupal/config/sync' ];
      then
        mkdir -p data/www/drupal/config/sync;
      fi
    - chmod -R 777 data/www/drupal/config/sync
    - scripts/drush si minimal -y
    - scripts/drush status
    - scripts/drush status >> report.txt
    - scripts/drupal site:status >> report.txt
    - scripts/composer show -P >> report.txt
  artifacts:
    paths:
      - report.txt
    expire_in: 1 hour
  cache:
    key: drupal
    paths:
      - data/www/drupal
      - data/database

.release:
  stage: release
  script:
    - echo "ok"
  only:
    - master
