image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - release

################################################################################
# Templates to avoid repeat.
# https://docs.gitlab.com/ee/ci/yaml/#anchors
################################################################################

################################################################################
# Jobs based on previous templates.
# Only variables need to be changed if needed.
################################################################################

build:
  stage: build
  script:
    - apk --no-cache add make gettext
    - make build

test:
  stage: test
  script:
    - apk --no-cache add make gettext bash python3
    - python3 -m ensurepip
    - pip3 install --upgrade pip setuptools
    - if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip; fi
    - if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi
    - pip install 'docker-compose'
    - make up
    - scripts/install-drupal.sh install drupal-min
    - scripts/drush status
  cache:
    paths:
      - /usr/bin/docker-compose

release:
  stage: release
  script:
    - echo "ok"
  only:
    - master
