image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  CONTAINER_WEB_ROOT: "/var/www/localhost/drupal"

################################################################################
# Templates to avoid repeat.
# https://docs.gitlab.com/ee/ci/yaml/#anchors
################################################################################

.install_docker_compose: &install_docker_compose
  before_script:
    - apk --no-cache add make gettext bash python3
    - python3 -m ensurepip
    - pip3 install --upgrade pip setuptools
    - if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip; fi
    - if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi
    - pip install 'docker-compose'

################################################################################
# Jobs based on previous templates.
# Only variables need to be changed if needed.
################################################################################

.build:
  stage: build
  <<: *install_docker_compose
  script:
    - make setup

test php 7.1:
  stage: test
  <<: *install_docker_compose
  script:
    - make setup
    - docker-compose up -d --build
    - docker exec dcd-php php -v
    - if [ ! -f 'data/www/drupal/web/index.php' ];
      then
        docker exec dcd-php composer create-project drupal-composer/drupal-project:8.x-dev $CONTAINER_WEB_ROOT --stability dev --no-interaction --quiet;
      fi
    - if [ ! -d 'data/www/drupal/config/sync' ];
      then
        mkdir -p data/www/drupal/config/sync;
      fi
    - chmod -R 777 data/www/drupal/config/sync
    - scripts/drush status
    - scripts/drush si minimal -y
    - scripts/drush status
  cache:
    key: drupal
    paths:
      - data/www/drupal
      - data/database

.test php 7.2:
  stage: test
  script:
    - apk --no-cache add make gettext bash python3
    - python3 -m ensurepip
    - pip3 install --upgrade pip setuptools
    - if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip; fi
    - if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi
    - pip install 'docker-compose'
    - make setup
    - sed -i 's#7.1#7.2#g' .env
    - docker-compose up -d --build
    - docker exec dcd-php php -v

.release:
  stage: release
  script:
    - echo "ok"
  only:
    - master
